name: cv-pytorch
channels:
  - pytorch
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - albumentations=1.3.1
  - alsa-lib=1.2.8
  - annotated-types=0.7.0
  - anyio=4.9.0
  - aom=3.5.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attr=2.5.1
  - attrs=25.3.0
  - babel=2.17.0
  - backoff=2.2.1
  - beautifulsoup4=4.13.4
  - blas=1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blessed=1.21.0
  - boto3=1.38.23
  - botocore=1.38.24
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.4.26
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.16.0
  - certifi=2025.4.26
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - comm=0.2.2
  - contourpy=1.3.1
  - croniter=1.4.1
  - cycler=0.11.0
  - dateutils=0.6.12
  - dbus=1.13.6
  - debugpy=1.8.11
  - decorator=5.2.1
  - deepdiff=7.0.1
  - defusedxml=0.7.1
  - dnspython=2.7.0
  - editor=1.6.6
  - email-validator=2.2.0
  - email_validator=2.2.0
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - fastapi=0.115.12
  - fastapi-cli=0.0.7
  - ffmpeg=5.1.2
  - fftw=3.3.10
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - fqdn=1.5.1
  - freeglut=3.2.2
  - freetype=2.13.3
  - gettext=0.24.1
  - gettext-tools=0.24.1
  - giflib=5.2.2
  - glib=2.80.2
  - glib-tools=2.80.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - graphite2=1.3.13
  - grpcio=1.54.3
  - gst-plugins-base=1.21.3
  - gstreamer=1.21.3
  - gstreamer-orc=0.4.41
  - h11=0.16.0
  - h2=4.2.0
  - harfbuzz=6.0.0
  - hdf5=1.14.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httptools=0.6.4
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=70.1
  - idna=3.10
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - inquirer=3.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.36.0
  - isoduration=20.11.0
  - itsdangerous=2.2.0
  - jack=1.9.22
  - jasper=2.0.33
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.1
  - jpeg=9e
  - json5=0.12.0
  - jsonpointer=2.1
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.24.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.8.0
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.3
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lazy-loader=0.4
  - lazy_loader=0.4
  - lcms2=2.15
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libabseil=20230125.3
  - libaec=1.1.3
  - libasprintf=0.24.1
  - libasprintf-devel=0.24.1
  - libblas=3.9.0
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcups=2.3.3
  - libcurl=8.1.2
  - libdb=6.2.32
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.10
  - libexpat=2.7.0
  - libffi=3.4.6
  - libflac=1.4.3
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt=1.11.1
  - libgcrypt-devel=1.11.1
  - libgcrypt-lib=1.11.1
  - libgcrypt-tools=1.11.1
  - libgettextpo=0.24.1
  - libgettextpo-devel=0.24.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.80.2
  - libglu=9.0.0
  - libgomp=15.1.0
  - libgpg-error=1.55
  - libgrpc=1.54.3
  - libiconv=1.18
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libltdl=2.4.3a
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopencv=4.7.0
  - libopus=1.5.2
  - libpciaccess=0.18
  - libpng=1.6.39
  - libpq=15.3
  - libprotobuf=3.21.12
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=253
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libtool=2.5.4
  - libudev1=253
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.51.0
  - libva=2.18.0
  - libvorbis=1.3.7
  - libvpx=1.11.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxcrypt=4.4.36
  - libxkbcommon=1.5.0
  - libxml2=2.10.3
  - libzlib=1.2.13
  - lightning-cloud=0.5.70
  - lz4-c=1.9.4
  - markdown=3.8
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.3
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpmath=1.3.0
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.4.2
  - notebook=7.4.3
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.100
  - numpy=1.26.4
  - numpy-base=1.26.4
  - opencv=4.7.0
  - openh264=2.3.1
  - openjpeg=2.5.0
  - openssl=3.1.8
  - ordered-set=4.1.0
  - orjson=3.10.18
  - overrides=7.7.0
  - p11-kit=0.24.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pcre2=10.43
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pixman=0.46.0
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - ply=3.11
  - prometheus_client=0.22.0
  - prompt-toolkit=3.0.51
  - protobuf=4.21.12
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio=16.1
  - pulseaudio-client=16.1
  - pulseaudio-daemon=16.1
  - pure_eval=0.2.3
  - py-opencv=4.7.0
  - pycparser=2.22
  - pydantic=2.1.1
  - pydantic-core=2.4.0
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.21.1
  - python-json-logger=2.0.7
  - python-multipart=0.0.20
  - python_abi=3.10
  - pytz=2025.2
  - pywavelets=1.8.0
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qt-main=5.15.6
  - qudida=0.0.4
  - re2=2023.03.02
  - readchar=4.2.0
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich-toolkit=0.11.3
  - rpds-py=0.22.3
  - runs=1.2.2
  - s3transfer=0.13.0
  - scikit-image=0.25.0
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - send2trash=1.8.3
  - shellingham=1.5.4
  - sip=6.7.12
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.7
  - sqlite=3.45.3
  - stack_data=0.6.3
  - starlette=0.46.2
  - starsessions=1.3.0
  - svt-av1=1.4.1
  - tbb=2021.8.0
  - tensorboard=2.19.0
  - tensorboard-data-server=0.7.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2025.2.18
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.5
  - traitlets=5.14.3
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - types-python-dateutil=2.9.0.20250516
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - uvicorn=0.34.2
  - uvicorn-standard=0.34.2
  - uvloop=0.21.0
  - watchfiles=1.0.5
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=12.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xmod=1.8.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - cg==0.1.0
      - docstring-parser==0.17.0
      - filelock==3.13.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - hydra-core==1.3.2
      - imageio-ffmpeg==0.6.0
      - iniconfig==2.3.0
      - jsonargparse==4.41.0
      - lightning==2.5.5
      - lightning-utilities==0.15.2
      - multidict==6.6.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.9.86
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.3.0
      - pip==25.2
      - pluggy==1.6.0
      - propcache==0.3.2
      - pygame==2.6.1
      - pytest==8.4.2
      - pytorch-lightning==2.5.5
      - rich==13.9.4
      - setuptools==80.9.0
      - sympy==1.13.1
      - tablut==0.1.0
      - tensorboardx==2.6.4
      - torch==2.5.1+cu121
      - torch-tb-profiler==0.4.3
      - torchaudio==2.5.1+cu121
      - torchmetrics==1.8.2
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - triton==3.1.0
      - typeshed-client==2.8.2
      - tzdata==2025.2
      - yarl==1.20.1
prefix: /home/larry/miniconda3/envs/cv-pytorch
